version: '3.8'

services:
  db_market:
    image: postgres:13
    container_name: db_market
    environment:
      POSTGRES_USER: soltayev
      POSTGRES_PASSWORD: myappl
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: